// see https://typst.app/universe/package/glossarium/
#let entry-list = (
  (
    key: "api",
    short: "API",
    plural: "API",
    long: "Application Programming Interface",
  ),
  (
    key: "bim",
    short: "BIM",
    plural: "BIM",
    long: "Building Information Modeling",
  ),
  (
    key: "blf",
    short: "BLF",
    plural: "BLF",
    long: "Blender Font Library",
  ),
  (
    key: "cad",
    short: "CAD",
    plural: "CAD",
    long: "Computer-Aided Design",
  ),
  (
    key: "dna",
    short: "DNA",
    plural: "DNA",
    long: "Data Architecture (Blender's internal C-structure layer)",
  ),
  (
    key: "dwg",
    short: "DWG",
    plural: "DWG",
    long: "Drawing — AutoCAD native binary format",
  ),
  (
    key: "dxf",
    short: "DXF",
    plural: "DXF",
    long: "Drawing Exchange Format",
  ),
  (
    key: "fbx",
    short: "FBX",
    plural: "FBX",
    long: "Filmbox — Autodesk proprietary 3D interchange format",
  ),
  (
    key: "gil",
    short: "GIL",
    plural: "GIL",
    long: "Global Interpreter Lock",
  ),
  (
    key: "gltf",
    short: "glTF",
    plural: "glTF",
    long: "GL Transmission Format",
  ),
  (
    key: "gn",
    short: "GN",
    plural: "GN",
    long: "Geometry Nodes",
  ),
  (
    key: "gpu",
    short: "GPU",
    plural: "GPU",
    long: "Graphics Processing Unit",
  ),
  (
    key: "hud",
    short: "HUD",
    plural: "HUD",
    long: "Heads-Up Display",
  ),
  (
    key: "ifc",
    short: "IFC",
    plural: "IFC",
    long: "Industry Foundation Classes",
  ),
  (
    key: "iso",
    short: "ISO",
    plural: "ISO",
    long: "International Organization for Standardization",
  ),
  (
    key: "json",
    short: "JSON",
    plural: "JSON",
    long: "JavaScript Object Notation",
  ),
  (
    key: "lmb",
    short: "LMB",
    plural: "LMB",
    long: "Left Mouse Button",
  ),
  (
    key: "mvc",
    short: "MVC",
    plural: "MVC",
    long: "Model-View-Controller",
  ),
  (
    key: "mvp",
    short: "MVP",
    plural: "MVP",
    long: "Minimum Viable Product",
  ),
  (
    key: "obj",
    short: "OBJ",
    plural: "OBJ",
    long: "Wavefront OBJ — open 3D geometry file format",
  ),
  (
    key: "pdf",
    short: "PDF",
    plural: "PDF",
    long: "Portable Document Format",
  ),
  (
    key: "rmb",
    short: "RMB",
    plural: "RMB",
    long: "Right Mouse Button",
  ),
  (
    key: "rna",
    short: "RNA",
    plural: "RNA",
    long: "Runtime Notification Architecture (Blender's Python-accessible reflection layer)",
  ),
  (
    key: "svg",
    short: "SVG",
    plural: "SVG",
    long: "Scalable Vector Graphics",
  ),
  (
    key: "ui",
    short: "UI",
    plural: "UI",
    long: "User Interface",
  ),
  (
    key: "uv",
    short: "UV",
    plural: "UV",
    long: "UV coordinates — 2D texture mapping coordinates",
  ),
  (
    key: "uuid",
    short: "UUID",
    plural: "UUID",
    long: "Universally Unique Identifier",
  ),
  (
    key: "ux",
    short: "UX",
    plural: "UX",
    long: "User Experience",
  ),
)
