#import "glossarium/glossarium.typ": gls

Cílem práce bylo navrhnout a implementovat addon pro Blender, který umožní parametrické a nedestruktivní modelování architektonických půdorysů. Tento cíl vychází z konkrétní mezery v ekosystému Blenderu: nativní polygonální modelování neumožňuje udržovat topologicky konzistentní dispozici při iterativních změnách bez ručního přepočítávání okolní geometrie. Zaplnění této mezery vyžadovalo nejen implementaci samotnou, ale i systematické pochopení potřeb tří odlišných cílových skupin --- architektů, 3D vizualizátorů a game designérů --- a překlad těchto potřeb do konkrétních funkčních a nefunkčních požadavků.

Analytická část práce zmapovala doménu parametrického modelování prostorových dispozic, provedla komparativní analýzu stávajících nástrojů uvnitř i vně Blenderu a formulovala šest skupin funkčních požadavků (FP1--FP7) se stanovenou #gls("mvp", long: false) prioritou. Tato prioritizace se ukázala jako klíčová: bez jasného oddělení must-have jádra od should-have a nice-to-have prvků by rozsah implementace nebyl udržitelný.

Návrhová část přeložila požadavky do třívrstvé hybridní architektury. Vrstva 1 (strukturální graf) odpovídá za topologii stěn a vrcholů; Vrstva 2 (sémantický graf místností) automaticky detekuje uzavřené cykly a udržuje metadata místností; Vrstva 3 (synchronizační vrstva) přenáší Python datový model do Blender meshe s pojmenovanými atributy čtenými modulem Geometry Nodes. Jednosměrný tok dat a striktní oddělení čistého Python jádra od Blender-závislých modulů se v průběhu implementace opakovaně potvrdily jako správné rozhodnutí.

Implementační část realizovala #gls("mvp", long: false) v plném rozsahu: interaktivní nástroj tužka pro kreslení stěn (FP1), parametrickou editaci stěn včetně polohy a přidávání otvorů (FP2), automatickou detekci a správu místností s výpočtem ploch (FP3) a finalizační operátor pro převod parametrického modelu na statický mesh (FP4). Implementace prošla řadou netriviálních technických problémů --- výkonnostní optimalizace tužkového nástroje, angular-sort algoritmus pro geometricky přesné stěnové spoje, numerická nestabilita dveřních cutterů v EXACT Boolean solveru --- jejichž řešení je v práci zdokumentováno. Automatizovaná testovací sada čítá přes 190 jednotkových testů pokrývající celé čisté Python jádro, přičemž všechny procházejí bez chyby.

Tři oblasti funkčního návrhu --- kontextové menu (FP5), 3D manipulátory (FP6) a automatické kótování (FP7) --- nebyly v rámci #gls("mvp", long: false) implementovány. Pro každou z nich je v kódu přichystán konkrétní opěrný bod: typovaný výsledek `_pick_element()` pro FP5, výstupy `junction_solver.py` a `move_junction_xy()` pro FP6, BLF draw handler a data Vrstvy 1 pro FP7. Stejně tak zůstávají neimplementována čtyři záměrně odložená omezení --- transformace objektu, duplikování, přejmenování a souběžná aktivace více FloorPlan objektů --- jejichž oprava nevyžaduje strukturální zásah do datového modelu.

Uživatelské testování neproběhlo z časových důvodů, avšak plán testování byl připraven: čtyři scénáře pokrývající celý workflow, dotazník zachycující dokončení úkolů, obtížnost a kvalitativní zpětnou vazbu, výběr účastníků ze všech tří cílových skupin. Na základě průběhu manuálního testování lze předpokládat, že uživatelské testování by identifikovalo zejména problémy s discoverabilitou aktivace FloorPlan módu a absencí vizuální zpětné vazby při omezování hodnot parametrů otvorů. Výstupy by pak přímo nasmírily rozsah iterační vývojové fáze.

FloorPlanMaster jako celek tvoří funkční a architektonicky připravený základ pro plnohodnotný veřejný addon. Třívrstvé jádro, centralizovaný overlay manager, synchronizační pipeline a detailně zdokumentované datové struktury umožňují pokračování vývoje bez nutnosti přepisovat existující logiku. Zbývající must-have rozšíření, nápravy provozních nedostatků a výsledky uživatelského testování přirozeně definují rozsah navazující fáze, která addon přiblíží vydání do komunity Blenderu.